require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MateriasController do

  # This should return the minimal set of attributes required to create a valid
  # Materia. As you add validations to Materia, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MateriasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all materias as @materias" do
      materia = Materia.create! valid_attributes
      get :index, {}, valid_session
      assigns(:materias).should eq([materia])
    end
  end

  describe "GET show" do
    it "assigns the requested materia as @materia" do
      materia = Materia.create! valid_attributes
      get :show, {:id => materia.to_param}, valid_session
      assigns(:materia).should eq(materia)
    end
  end

  describe "GET new" do
    it "assigns a new materia as @materia" do
      get :new, {}, valid_session
      assigns(:materia).should be_a_new(Materia)
    end
  end

  describe "GET edit" do
    it "assigns the requested materia as @materia" do
      materia = Materia.create! valid_attributes
      get :edit, {:id => materia.to_param}, valid_session
      assigns(:materia).should eq(materia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Materia" do
        expect {
          post :create, {:materia => valid_attributes}, valid_session
        }.to change(Materia, :count).by(1)
      end

      it "assigns a newly created materia as @materia" do
        post :create, {:materia => valid_attributes}, valid_session
        assigns(:materia).should be_a(Materia)
        assigns(:materia).should be_persisted
      end

      it "redirects to the created materia" do
        post :create, {:materia => valid_attributes}, valid_session
        response.should redirect_to(Materia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved materia as @materia" do
        # Trigger the behavior that occurs when invalid params are submitted
        Materia.any_instance.stub(:save).and_return(false)
        post :create, {:materia => {}}, valid_session
        assigns(:materia).should be_a_new(Materia)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Materia.any_instance.stub(:save).and_return(false)
        post :create, {:materia => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested materia" do
        materia = Materia.create! valid_attributes
        # Assuming there are no other materias in the database, this
        # specifies that the Materia created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Materia.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => materia.to_param, :materia => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested materia as @materia" do
        materia = Materia.create! valid_attributes
        put :update, {:id => materia.to_param, :materia => valid_attributes}, valid_session
        assigns(:materia).should eq(materia)
      end

      it "redirects to the materia" do
        materia = Materia.create! valid_attributes
        put :update, {:id => materia.to_param, :materia => valid_attributes}, valid_session
        response.should redirect_to(materia)
      end
    end

    describe "with invalid params" do
      it "assigns the materia as @materia" do
        materia = Materia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Materia.any_instance.stub(:save).and_return(false)
        put :update, {:id => materia.to_param, :materia => {}}, valid_session
        assigns(:materia).should eq(materia)
      end

      it "re-renders the 'edit' template" do
        materia = Materia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Materia.any_instance.stub(:save).and_return(false)
        put :update, {:id => materia.to_param, :materia => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested materia" do
      materia = Materia.create! valid_attributes
      expect {
        delete :destroy, {:id => materia.to_param}, valid_session
      }.to change(Materia, :count).by(-1)
    end

    it "redirects to the materias list" do
      materia = Materia.create! valid_attributes
      delete :destroy, {:id => materia.to_param}, valid_session
      response.should redirect_to(materias_url)
    end
  end

end
